### ISSUE TITLE
NodaTime 3.0

### ISSUE THREAD

**Issue by ackginger** [kingboyk/Serilog.NodaTime#6]
Hi

I see you have a 3.0 branch waiting to merge. Now NodaTime 3 is out of beta are you planning on merging and releasing this any time soon?

Thanks

Adam

**Comment by lundmikkel** [comment]
@kingboyk We are currently not able to update our NodaTime version to 3.0, because we consume this package, which limits the NodaTime version to `[2.3,3.0)`. I threw together a quick fix,, but I can see your 3.0 branch is much more extensive. Could you please release this branch, so we can update things on our end?

**Comment by kingboyk** [comment]
A release version of v3 is now available on Nuget. Please reopen if there are any problems.
